// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZavrsniRad.Models;

namespace ZavrsniRad.Migrations
{
    [DbContext(typeof(ZavrsniRadContext))]
    [Migration("20190621215644_AddedOpcinaToZupanija")]
    partial class AddedOpcinaToZupanija
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ZavrsniRad.Models.Država", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Države");
                });

            modelBuilder.Entity("ZavrsniRad.Models.Igrač", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .IsRequired();

                    b.Property<string>("Prezime")
                        .IsRequired();

                    b.Property<int>("TimId");

                    b.HasKey("Id");

                    b.HasIndex("TimId");

                    b.ToTable("Igrači");
                });

            modelBuilder.Entity("ZavrsniRad.Models.Nagrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IgračId");

                    b.Property<string>("Ime")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("IgračId");

                    b.ToTable("Nagrade");
                });

            modelBuilder.Entity("ZavrsniRad.Models.Natjecanja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datum_odigravanja");

                    b.Property<string>("Ime");

                    b.Property<int>("Ukupno_timova");

                    b.HasKey("Id");

                    b.ToTable("Natjecanje");
                });

            modelBuilder.Entity("ZavrsniRad.Models.Općina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .IsRequired();

                    b.Property<int>("ŽupanijaId");

                    b.HasKey("Id");

                    b.HasIndex("ŽupanijaId");

                    b.ToTable("Općine");
                });

            modelBuilder.Entity("ZavrsniRad.Models.Tim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Broj_igraca");

                    b.Property<int>("Godine_igranja");

                    b.Property<string>("Ime")
                        .IsRequired();

                    b.Property<bool>("Kotizacija");

                    b.HasKey("Id");

                    b.ToTable("Timovi");
                });

            modelBuilder.Entity("ZavrsniRad.Models.Županija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DržavaId");

                    b.Property<string>("Ime");

                    b.HasKey("Id");

                    b.HasIndex("DržavaId");

                    b.ToTable("Županije");
                });

            modelBuilder.Entity("ZavrsniRad.Models.Igrač", b =>
                {
                    b.HasOne("ZavrsniRad.Models.Tim", "Tim")
                        .WithMany("Igrači")
                        .HasForeignKey("TimId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ZavrsniRad.Models.Nagrada", b =>
                {
                    b.HasOne("ZavrsniRad.Models.Igrač", "Igrač")
                        .WithMany()
                        .HasForeignKey("IgračId");
                });

            modelBuilder.Entity("ZavrsniRad.Models.Općina", b =>
                {
                    b.HasOne("ZavrsniRad.Models.Županija", "Županija")
                        .WithMany("Općine")
                        .HasForeignKey("ŽupanijaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ZavrsniRad.Models.Županija", b =>
                {
                    b.HasOne("ZavrsniRad.Models.Država", "Država")
                        .WithMany("Županije")
                        .HasForeignKey("DržavaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
